on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  build_test_package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Configure project
        run: cmake -B build

      - name: Build project and tests
        run: cmake --build build --parallel

      - name: Run tests
        run: cd build && ctest --output-on-failure

      - name: Build DEB package
        if: startsWith(github.ref, 'refs/tags/')
        run: cd build && cpack -G DEB

      - name: Upload DEB artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: adapter-pattern-deb
          path: build/*.deb
          retention-days: 1

  create_release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build_test_package
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download DEB package
        uses: actions/download-artifact@v4
        with:
          name: adapter-pattern-deb
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Adapter Pattern ${{ github.ref_name }}
          body: DEB package for Adapter Pattern implementation
          files: artifacts/*.deb
